Wip/32 usuwanie oferty
aidian3k/caterly pull request #110
Opened 2024-12-02 22:01 UTC by gardyjam

-> zmiana endpointów (po stronie FE) do pokazywania listy posiłków i usuwania ich 
-> jeśli znowu są problemy z ikonami/plikami to przepraszam

2024-12-02 22:04 UTC, igorkedzierawski requested changes

2024-12-02 22:04 UTC, igorkedzierawski commented on caterly-client-frontend/package.json
> +    "caterly-client-frontend": "file:",
tylko nie ten branch :sob:

2024-12-02 22:10 UTC, igorkedzierawski commented on caterly-client-frontend/package.json
> +    "caterly-client-frontend": "file:",
proponuję aby @CezaryS8 zrobił brancha ze swoim fixem, i potem do tamtego brancha domergujesz swoją zmianę (tak imo będzie najsensowniej)

2024-12-02 22:15 UTC, gardyjam commented on caterly-client-frontend/package.json
> +    "caterly-client-frontend": "file:",
a jaki dokładnie problem jest z tym branchem? starałam się zachować pliki takie jak w main, zostawić tylko poprawkę api, więc trochę nie rozumiem różnicy

2024-12-02 22:19 UTC, igorkedzierawski commented on caterly-client-frontend/package.json
> +    "caterly-client-frontend": "file:",
zmiana wydaje się niewielka, a pr ma 21 commitów i zmienia 16 plików, przez co trudno zobaczyć jaka zmiana była intencją tego pr'a.
jak stworzysz nowego brancha z maina to będzie to o wiele czyściej wyglądać

2024-12-03 18:17 UTC, gardyjam commented on caterly-client-frontend/package.json
> +    "caterly-client-frontend": "file:",
zrozumiałe, postaram się zrobić to jutro rano

2024-12-05 16:33 UTC, closed without merging

2024-12-05 16:33 UTC, gardyjam commented
nieaktualne