Wip/32 usuwanie oferty
aidian3k/caterly pull request #98
Opened 2024-11-26 21:35 UTC by gardyjam

[FE] Usuwanie oferty firmy kateringowej

2024-11-27 19:03 UTC, igorkedzierawski reviewed
proponuję odwrócić zmiany do tych plików
backend/cateringClientService/gradlew.bat
backend/cateringCompanyService/gradlew.bat
backend/gatewayService/gradlew.bat
caterly-catering-company-frontend/package.json
caterly-catering-company-frontend/public/favicon.ico
caterly-catering-company-frontend/public/logo192.png
caterly-catering-company-frontend/public/logo512.png
caterly-catering-company-frontend/src/index.tsx
caterly-catering-company-frontend/src/webpack.config.js
caterly-catering-company-frontend/yarn.lock
caterly-client-frontend/package-lock.json
caterly-client-frontend/package.json
caterly-client-frontend/public/favicon.ico
caterly-client-frontend/public/logo192.png
caterly-client-frontend/public/logo512.png
caterly-client-frontend/yarn.lock

2024-11-27 19:03 UTC, igorkedzierawski commented on caterly-catering-company-frontend/public/logo192.png
nw jak u ciebie, ale u mnie wszystkie te obrazki się popsuły

2024-11-27 19:03 UTC, igorkedzierawski commented on caterly-catering-company-frontend/src/components/features/offer/OfferItem.component.tsx
> +                className="mt-4 px-4 py-2 bg-red-500 text-white rounded hover:bg-red-600 transition duration-200 ease-in-out"
czy ten pr przypadkiem nie usuwa tailwinda?

2024-11-27 20:01 UTC, KubaOrz requested changes

2024-11-27 20:07 UTC, gardyjam commented
najwyraźniej mój lokalny system coś sam namieszał (np. te obrazki zmienia automatycznie, nie mogę nawet ich zrestorować, bo od razu zmieniają się na nowo), powprowadzam te zmiany, o których piszecie i spróbuję jeszcze raz

2024-11-28 11:11 UTC, gardyjam commented
wprowadziłam zmiany i pipeline już cały przechodzi, dziękuję! 

nie zmieniłam plików wskazanych przez Igora, bo, jak pisałam wcześniej, mój lokalny system sam podmienia je automatycznie. z tego co kojarzę te ikonki i tak nie są nigdzie używane, ale co najwyżej ktoś inny może je nadpisać przy innym commit'cie

2024-11-28 11:41 UTC, igorkedzierawski commented
>mój lokalny system sam podmienia je automatycznie.

I got this

2024-11-29 21:39 UTC, closed without merging